### ISSUE TITLE
Ask! 

### ISSUE THREAD

**Issue by root9464** [react-map/react-map#22]
can I somehow highlight the area I need on the map?

**Comment by shubhexists** [comment]
Not yet 
Was working on it but as of now no :smiley:

**Comment by shubhexists** [comment]
It would need me to make docs and reveal the specific tags of each map...
hence would be an effort to implement

**Comment by root9464** [comment]
> It would need me to make docs and reveal the specific tags of each map...
> hence would be an effort to implement
> 
> Thanks for asking though :D
> Gives me motivation to work on it faster lol

I just like it took the list and Yandex maps or Google maps I don't like that there's area and came across your library , looked at the code and saw that she was quite fresh and it no legacy . Therefore, I wish you a successful development

**Comment by shubhexists** [comment]
Hi @root9464 , just a heads up if you still need it : D
You can now pass it a cityColors map 
 `cityColors = {},` in the components to pass custom colours to the city/state..
 
 So, you can highlight the area you need with your colours: )
 
 Yet to update the docs though
